name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - 
      name: Checkout files
      uses: actions/checkout@v1
    - 
      name: Install armv7 cross compiler
      run: |
        sudo apt update
        sudo apt install -y build-essential libc6-armel-cross libc6-dev-armel-cross binutils-arm-linux-gnueabi libncurses5-dev gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
    -
       name: Run build
       run: |
        CC=arm-linux-gnueabi-gcc ./release.sh binary
        
    - 
      name: Upload the artifact 
      uses: actions/upload-artifact@v1
      with:
        name: quickjs-build
        path: /tmp/quickjs-linux-x86_64-2019-12-21.zip
